# 登陆后的JSESSIONID
JSESSIONID: XXXXXXXXXXXX
#  预约日期，可以多选，列表格式， 格式必须是：yyyy-MM-dd
bookDateList:
  #- 2019-12-07
  - 2019-12-19
#  景区名称，必须取 SubscribeIdEnum 中对应的名称
subscribeName: 中央广播电视塔
emailNotice: true
#  是否开启定时抢票
timing: false
#  设置开抢的定时时间，别写错了，这个时间一般是预约日期往前三天。
timingStartTimeConfig: '2019-12-19 06:55'
#  预约截止时间，防止在此时间点之后约到票了但是来不及赶去景点,最大不应超过预约日期+24h
endTimeConfig: '2019-12-19 18:00'
#  预约卡号列表
cardNoList:
  - XXXXXXXXXX
